#ifndef THPLUGINPAGEVIEW_GLOBAL_H
#define THPLUGINPAGEVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(THPLUGINPAGEVIEW_LIBRARY)
#  define THPLUGINPAGEVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define THPLUGINPAGEVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // THPLUGINPAGEVIEW_GLOBAL_H
